bench_name: arena-hard-v2.0
# bench_name: tmp

# a list of model to generate answers
model_list:
  # - gemini-2.0-flash-lite-001
  # - gemini-2.5-pro
  # - gemini-2.0-flash-001
  # - gemini-2.0-flash-lite
  # - gemini-2.0-flash
  # - gemini-2.5-flash
  - meta/llama-3.3-70b-instruct-maas
  - meta/llama-4-maverick-17b-128e-instruct-maas
  - meta/llama-4-scout-17b-16e-instruct-maas
  - claude-3-7-sonnet@20250219
  - claude-sonnet-4@20250514
  - claude-3-5-haiku@20241022
  - claude-opus-4@20250514
  - mistral-large-2411
  - mistral-small-2503@001
